apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: argocd-server
  namespace: tools-argo
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-staging
    kubernetes.io/tls-acme: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    argocd.argoproj.io/sync-wave: "72"
spec:
  rules:
    - http:
        paths:
        - path: /
          pathType: ImplementationSpecific
          backend:
            service:
             name: abhra-argocd-server
             port:
               number: 80
      host: cd.argo.staging.abhra.shambhala.cloud
  tls:
    - hosts:
      - cd.argo.staging.abhra.shambhala.cloud
      secretName: argocd-server-cert
